### ISSUE TITLE
Ability to merge DOCS to main. 

### ISSUE THREAD

**Issue by Romes8** [Eagles-DevOps/MiniTwit#191]
Crete and action that will be able to push the DOCS folder to the main without the need to create a PR. 

There is a BOT user that should be able to push to the main without the need of PR. That can be one way how to approach this. 

Another tip can be seen in deployment file for the automated release where we state the permission for that specific action: 

```
permissions:
    actions: write
    contents: write
    deployments: write
    packages: write
    repository-projects: write
```
